### PR TITLE
Carnivore GA tracker

### PR DESCRIPTION
**Pull request by brmscheiner**

### CODE REVIEW

**Comment by arielmirra** [comment]
Hi! sorry to comment here, but I'm a software engineer looking to contribute to this project (found it in explore.ovio.org) but can't seem to find a contributing.md or something like that. Is this project open-source? how can I contribute? Thanks!

**Comment by brmscheiner** [comment]
@arielmirra no problem! At the moment there are some docs but they are not completely up-to-date. How were you looking to get involved?

**Comment by arielmirra** [comment]
@brmscheiner I know Java, I'm a native Spanish speaker and I don't have a huge amount of time. So I'm looking for things like Refactors, PRs, TODOs, testing or even translating the docs. Anything that doesn't require much deep knowledge about the full project but can make a difference in it.

**Comment by brmscheiner** [comment]
Hey @arielmirra, sorry for the delay!! We had to have a group discussion since at the moment we don't provide enough resources to make it easy to contribute. Here is what would be very helpful for us:

1. Try using the [installation manual](https://www.wildbook.org/doku.php?id=documentation#installation) to get the project running on your system 
2. Provide feedback on the existing documentation, let us know what improvement is needed
3. If you get stuck or run into trouble, post a question on [community.wildbook.org](community.wildbook.org). This is a new support forum we are trying to get rolling, so you would basically be the first poster. I promise we will respond :)

Feel free to bow out if it doesn't sound interesting, but I can promise this would be very helpful for us!

**Pull request merged**
